feat(improvement): add port option to the share command
mus-inn/devcontainer-dotworld pull request #39
Opened 2024-08-28 08:48 UTC by dokeanos

[skip ci]

2024-08-28 09:55 UTC, gtko requested changes

2024-08-28 09:55 UTC, gtko commented on dotdev/commands/share.sh
> +share_url="${share_url}:${port}"
ces deux params rentre en conflict par normalement la command ce gère comme ceci : 
soit on mets rien ```dotdev share```et il p^rend automatiquement 127.0.0.1:80 , soit on rentre direct l'url qu'on veut ```dotdev share http://127.0.0.1:8000``` du coup si tu laisse --port ça peut nous donner un truc de ce style : 
``` http://127.0.0.1:8000:90```

2024-08-28 14:53 UTC, dokeanos commented on dotdev/commands/share.sh
> +share_url="${share_url}:${port}"
J'ai fix dans le dernier push

2024-08-29 08:54 UTC, gtko approved these changes

2024-08-29 08:55 UTC, merged